- id_category: 60
  source_category: Aksesuarai
  marketplace_category: Pižamos ir naktiniai
- id_category: 73
  source_category: Aksesuarai
  marketplace_category: Apatinis trikotažas moterims
- id_category: 56
  source_category: Apatinės kelnės
  marketplace_category: Termo rūbai
- id_category: 28
  source_category: Apatiniai Šortukai
  marketplace_category: Apatinis trikotažas moterims
- id_category: 926
  source_category: Apatinis trikotažas
  marketplace_category: Apatinis trikotažas moterims
- id_category: 24
  source_category: Apatinukės, Pasijoniai
  marketplace_category: Pižamos ir naktiniai
- id_category: 89
  source_category: Balconette (bardot) Liemenėlės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 454
  source_category: Bandeau modeliai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 451
  source_category: Bikiniai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 4282
  source_category: Bodžiai ir Kūno triko
  marketplace_category: Seksualios kojinės
- id_category: 52
  source_category: Bokseriai
  marketplace_category: Vyriški apatiniai
- id_category: 4329
  source_category: Chalatai
  marketplace_category: Chalatai
- id_category: 150
  source_category: Chalatai Vyrams
  marketplace_category: Chalatai
- id_category: 26
  source_category: Diržai (juosmenėliai) kojinėms
  marketplace_category: Kojinės moterims
- id_category: 93
  source_category: Dviejų dalių maudymukai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 140
  source_category: Džemperiai
  marketplace_category: Džemperiai moterims
- id_category: 4283
  source_category: Erotiniai Teminiai kostiumai
  marketplace_category: Seksualūs kostiumai
- id_category: 4284
  source_category: Erotiški apatinių komplektai
  marketplace_category: Seksualūs kostiumai
- id_category: 4330
  source_category: Frotiniai ir Šilti Chalatai
  marketplace_category: Chalatai
- id_category: 88
  source_category: Funkcinės liemenėlės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 2242
  source_category: Funkcinės pėdkelnės
  marketplace_category: Pėdkelnės moterims
- id_category: 75
  source_category: Glaudės Vyrams
  marketplace_category: Paplūdimio apranga vyrams
- id_category: 1832
  source_category: Glaustinukės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 929
  source_category: Jam
  marketplace_category: Apranga vyrams
- id_category: 27
  source_category: Kelnaitės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 148
  source_category: Kelnės
  marketplace_category: Kelnės moterims
- id_category: 290
  source_category: Kepurės
  marketplace_category: Kepurės
- id_category: 173
  source_category: Kepurės Paplūdimiui
  marketplace_category: Maudymosi kostiumėliai
- id_category: 933
  source_category: Kepurės, šalikai, pirštinės
  marketplace_category: Apranga, avalynė, aksesuarai
- id_category: 1303
  source_category: Kojinės
  marketplace_category: Kojinės moterims
- id_category: 96
  source_category: Kojinės iki kelių
  marketplace_category: Kojinės moterims
- id_category: 94
  source_category: Kojinės virš kelių
  marketplace_category: Kojinės moterims
- id_category: 934
  source_category: Kombinezonai
  marketplace_category: Kombinezonai
- id_category: 25
  source_category: Komplektai
  marketplace_category: Pižamos ir naktiniai
- id_category: 23
  source_category: Korsetai
  marketplace_category: Apatinis trikotažas moterims
- id_category: 4300
  source_category: Krepšiai paplūdimiui
  marketplace_category: Maudymosi kostiumėliai
- id_category: 408
  source_category: Kūno kojinės, triko
  marketplace_category: Seksualios kojinės
- id_category: 935
  source_category: Laisvalaikio apranga
  marketplace_category: Sportinė apranga moterims
- id_category: 4299
  source_category: Laisvalaikio komplektai
  marketplace_category: Sportinė apranga moterims
- id_category: 2473
  source_category: Liekninančios, modeliuojančios kelnaitės
  marketplace_category: Koreguojantys drabužiai moterims
- id_category: 20
  source_category: Liemenėlės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 83
  source_category: Liemenėlės kietais kaušeliais
  marketplace_category: Apatinis trikotažas moterims
- id_category: 80
  source_category: Liemenėlės Minkštais kaušeliais
  marketplace_category: Apatinis trikotažas moterims
- id_category: 85
  source_category: Liemenėlės nuimamomis petnešėlėmis
  marketplace_category: Apatinis trikotažas moterims
- id_category: 82
  source_category: Liemenėlės su paminkštinimu
  marketplace_category: Apatinis trikotažas moterims
- id_category: 81
  source_category: Liemenėlės su Push-Up
  marketplace_category: Apatinis trikotažas moterims
- id_category: 171
  source_category: Lietpalčiai
  marketplace_category: Paltai moterims
- id_category: 58
  source_category: Maudymosi drabužiai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 280
  source_category: Maudymosi kelnaitės
  marketplace_category: Maudymosi kostiumėliai
- id_category: 931
  source_category: Maudymosi kostiumėliai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 358
  source_category: Maudymosi šortai
  marketplace_category: Paplūdimio apranga vyrams
- id_category: 4331
  source_category: Medvilniniai Chalatai
  marketplace_category: Chalatai
- id_category: 100
  source_category: Miego drabužiai
  marketplace_category: Pižamos ir naktiniai
- id_category: 925
  source_category: Miegui, nakčiai
  marketplace_category: Pižamos ir naktiniai
- id_category: 1953
  source_category: Monokini Maudymukai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 44
  source_category: Moteriški Chalatai
  marketplace_category: Chalatai
- id_category: 932
  source_category: Moteriški drabužiai
  marketplace_category: Apranga moterims
- id_category: 99
  source_category: Moteriškos Apatinės Kelnaitės
  marketplace_category: Apatinis trikotažas moterims
- id_category: 59
  source_category: Moteriškos pižamos
  marketplace_category: Pižamos ir naktiniai
- id_category: 1951
  source_category: Naktinukai, naktiniai marškiniai
  marketplace_category: Pižamos ir naktiniai
- id_category: 1586
  source_category: Namų Drabužiai
  marketplace_category: Sportinė apranga moterims
- id_category: 136
  source_category: Palaidinės
  marketplace_category: Palaidinės, tunikos moterims
- id_category: 590
  source_category: Palaidinės ilgomis rankovėmis
  marketplace_category: Palaidinės, tunikos moterims
- id_category: 577
  source_category: Palaidinės trumpomis rankovėmis
  marketplace_category: Palaidinės, tunikos moterims
- id_category: 4333
  source_category: Paplūdimio Drabužėliai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 1587
  source_category: Paplūdimio Sijonėliai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 174
  source_category: Paplūdimio Tunikos
  marketplace_category: Maudymosi kostiumėliai
- id_category: 172
  source_category: Parea
  marketplace_category: Maudymosi kostiumėliai
- id_category: 95
  source_category: Pėdkelnės lygios
  marketplace_category: Pėdkelnės moterims
- id_category: 410
  source_category: Pėdkelnės su raštais
  marketplace_category: Pėdkelnės moterims
- id_category: 61
  source_category: Pėdkelnės, Kojinės, Juosmenėliai
  marketplace_category: Pėdkelnės moterims
- id_category: 126
  source_category: Pirštinės
  marketplace_category: Pirštinės
- id_category: 930
  source_category: Priedai, Aksesuarai
  marketplace_category: Seksualus apatinis trikotažas
- id_category: 452
  source_category: Push-up Maudymukai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 30
  source_category: Seksualios Glaustinukės (body)
  marketplace_category: Seksualūs korsetai
- id_category: 4280
  source_category: Seksualios kelnaitės
  marketplace_category: Seksualios kelnaitės
- id_category: 102
  source_category: Seksualūs apatiniai
  marketplace_category: Seksualus apatinis trikotažas
- id_category: 4281
  source_category: Seksualūs naktinukai
  marketplace_category: Pižamos ir naktiniai
- id_category: 29
  source_category: Siaurikės (stringai)
  marketplace_category: Apatinis trikotažas moterims
- id_category: 138
  source_category: Sijonai
  marketplace_category: Sijonas moterims
- id_category: 127
  source_category: Sportinė, aktyvumo apranga
  marketplace_category: Sportinė apranga moterims
- id_category: 135
  source_category: Suknelės
  marketplace_category: Suknelės moterims
- id_category: 291
  source_category: Šalikai
  marketplace_category: Šalikai, skraistės
- id_category: 4334
  source_category: Šlepetės
  marketplace_category: Šlepetės
- id_category: 176
  source_category: Švarkai
  marketplace_category: Švarkeliai moterims
- id_category: 97
  source_category: Tamprės (leginsai)
  marketplace_category: Tamprės
- id_category: 205
  source_category: Tankini Maudymukai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 450
  source_category: Trijų dalių maudymukai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 50
  source_category: Trumpikės
  marketplace_category: Vyriški apatiniai
- id_category: 292
  source_category: Tunikos
  marketplace_category: Maudymosi kostiumėliai
- id_category: 92
  source_category: Vientisi maudymosi kostiumėliai
  marketplace_category: Maudymosi kostiumėliai
- id_category: 46
  source_category: Vyrams
  marketplace_category: Apranga vyrams
- id_category: 922
  source_category: Vyriški Apatiniai
  marketplace_category: Vyriški apatiniai
- id_category: 4321
  source_category: Vyriški Chalatai
  marketplace_category: Chalatai
- id_category: 47
  source_category: Vyriški Marškinėliai
  marketplace_category: Marškinėliai vyrams
- id_category: 54
  source_category: Vyriški stringai
  marketplace_category: Vyriški apatiniai
- id_category: 149
  source_category: Vyriškos Kojinės
  marketplace_category: Kojinės vyrams
- id_category: 57
  source_category: Vyriškos Pižamos
  marketplace_category: Pižamos ir naktiniai
- id_category: 4320
  source_category: Vyriškos Pižamos
  marketplace_category: Pižamos ir naktiniai
- id_category: 4332
  source_category: Viskoziniai Chalatai
  marketplace_category: Chalatai
- id_category: 4292
  source_category: Žaidimų aksesuarai
  marketplace_category: Seksualus apatinis trikotažas
